version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps)"
    groups:
      next-framework:
        applies-to: version-updates
        patterns:
          - "next"
          - "eslint-config-next"
        update-types:
          - "minor"
          - "patch"
      npm-minor-and-patch:
        applies-to: version-updates
        patterns:
          - "*"
        exclude-patterns:
          - "next"
          - "eslint-config-next"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(ci)"
